INSERT INTO db.user (userID, username, password, logged, type) VALUES (1, 'ale', 'ale', 0, 0);
INSERT INTO db.user (userID, username, password, logged, type) VALUES (2, 'tudor', 'tudor', 0, 0);
INSERT INTO db.user (userID, username, password, logged, type) VALUES (3, 'bogdan', 'bogdan', 1, 0);
INSERT INTO db.user (userID, username, password, logged, type) VALUES (4, 'cristi', 'cristi', 0, 0);
INSERT INTO db.user (userID, username, password, logged, type) VALUES (5, 'garleanu', 'garleanu', 0, 0);
INSERT INTO db.user (userID, username, password, logged, type) VALUES (6, 'mihai', 'mihai', 0, 0);
INSERT INTO db.user (userID, username, password, logged, type) VALUES (7, 'rata', 'rata', 0, 0);
INSERT INTO db.user (userID, username, password, logged, type) VALUES (8, 'alexxxx', 'alex', 0, 0);
INSERT INTO db.user (userID, username, password, logged, type) VALUES (9, 'alexxx', 'alexxx', 0, 0);